#!/usr/bin/env python3
"""
case_state_generator.py — the case state schemas (F9 build 3).

F9's reasoning for building this one: **this skill is the suite's state owner, so
hand-assembled state is the worst place in the suite for drift.** Every other skill reads
what this one writes. A malformed `_case_file.json` does not fail loudly here; it fails
later, somewhere else, as a wrong answer.

Builds and validates:
    _case_file.json                 the single source of truth for a case
    team_binding.json               the Teams binding decision, made once
    rfx_project_acknowledged.json   the Project acknowledgement gate
    meeting_log.csv                 a log

Meeting drafts, comms and status snapshots stay PROSE (F9): they are communication.
The Case Status Visual stays deferred, pending the hub decision.

WHAT IT REFUSES TO DO
---------------------
  * a `status` or `current_phase` outside the documented enum      -> EnumError
  * a `schema_version` this generator does not implement           -> SchemaVersionError
  * duplicate `supplier_id`, stakeholder or event id               -> DuplicateIdError
  * **a case_id that CHANGES when ingesting a case_handoff**       -> CaseIdError
  * a missing case_id or case_title                                -> SchemaError

The case_id rule is the one worth stating twice. SKILL.md: the case_id is "generated by
this skill, OR PRESERVED AS-IS from an inbound case_handoff.json". Regenerating it on
ingest silently forks one sourcing event into two records, and every downstream skill that
keyed off the original id then points at a case that no longer accumulates history. It is a
data-loss bug that looks like a successful import.

Stdlib only.
"""
from __future__ import annotations

import csv
import json
import os
import re
import sys

SCHEMA_VERSION = "2.3"

STATUS = ("Draft", "Active", "On Hold", "Awarded", "Cancelled", "Closed")
PHASE = ("Pre-Issue", "Q&A Window", "Post-Submission", "Demo", "Reference",
         "BAFO", "Decision", "Close")
STAKEHOLDER_ROLES = ("Lead", "Functional Evaluator", "Technical Evaluator",
                     "Approver", "Observer")

CASE_ID_RE = re.compile(r"^RFP-\d{4}-\d{3}$")          # this skill's own format
HANDOFF_ID_RE = re.compile(r"^RFP-\d{8}-[a-z0-9\-]+$")  # rfp-engine's format


class CaseStateError(Exception):
    """Base for every refusal."""


class SchemaError(CaseStateError):
    pass


class EnumError(CaseStateError):
    pass


class SchemaVersionError(CaseStateError):
    pass


class DuplicateIdError(CaseStateError):
    pass


class CaseIdError(CaseStateError):
    pass


def _enum(value, allowed, field):
    if value not in allowed:
        raise EnumError(
            "%s is %r, which is outside the documented enum. An unrecognised value is not "
            "a new state, it is a typo that every downstream reader will mishandle. "
            "Allowed: %s" % (field, value, " | ".join(allowed))
        )


def _unique(rows, key, label):
    seen = set()
    for i, r in enumerate(rows or []):
        v = r.get(key)
        if v is None:
            raise SchemaError("%s[%d] has no %s" % (label, i, key))
        if v in seen:
            raise DuplicateIdError(
                "duplicate %s %r in %s. Two rows sharing an id means one of them is "
                "unreachable: any lookup returns the first and the second silently never "
                "applies." % (key, v, label)
            )
        seen.add(v)


def validate_case_file(case):
    """Full validation of `_case_file.json`. Returns the case unchanged when valid."""
    if not isinstance(case, dict):
        raise SchemaError("case file must be an object, got %s" % type(case).__name__)

    ver = case.get("schema_version")
    if ver != SCHEMA_VERSION:
        raise SchemaVersionError(
            "schema_version is %r; this generator implements %r. Refusing to write state "
            "under a version it does not understand: a silently upgraded or downgraded "
            "case file is how one skill's assumption becomes another skill's wrong answer."
            % (ver, SCHEMA_VERSION)
        )

    for field in ("case_id", "case_title"):
        if not (case.get(field) or "").strip():
            raise SchemaError("%s is required and must be non-empty" % field)

    _enum(case.get("status"), STATUS, "status")
    _enum(case.get("current_phase"), PHASE, "current_phase")

    _unique(case.get("suppliers"), "supplier_id", "suppliers")
    _unique(case.get("events"), "event_id", "events")

    for i, s in enumerate(case.get("stakeholders") or []):
        role = s.get("role")
        if role is not None:
            _enum(role, STAKEHOLDER_ROLES, "stakeholders[%d].role" % i)

    # A closed case with an open phase is internally inconsistent. Cheap to check, and the
    # kind of contradiction a human reader skims past.
    if case.get("status") in ("Closed", "Cancelled") and case.get("current_phase") not in ("Close", None):
        raise SchemaError(
            "status is %r but current_phase is %r. A finished case cannot still be in an "
            "active phase; one of the two was updated and the other was not."
            % (case["status"], case["current_phase"])
        )
    return case


def ingest_handoff(case, handoff):
    """Merge an rfp-engine `case_handoff.json` into a case file.

    The case_id is PRESERVED, never regenerated. See the module docstring.
    """
    if not isinstance(handoff, dict):
        raise SchemaError("handoff must be an object")
    incoming = (handoff.get("case_id") or "").strip()
    if not incoming:
        raise SchemaError("handoff carries no case_id; there is nothing to preserve")

    existing = (case.get("case_id") or "").strip()
    if existing and existing != incoming:
        raise CaseIdError(
            "case_id conflict: the case file holds %r and the handoff carries %r. Refusing "
            "to choose. Overwriting either one forks a single sourcing event into two "
            "records, and every skill keyed to the discarded id then points at a case that "
            "stops accumulating history." % (existing, incoming)
        )

    merged = dict(case)
    merged["case_id"] = incoming          # preserved as-is, whichever format it is in
    merged["schema_version"] = SCHEMA_VERSION
    for field in ("case_title", "category"):
        if handoff.get(field) and not merged.get(field):
            merged[field] = handoff[field]
    merged.setdefault("status", "Draft")
    merged.setdefault("current_phase", "Pre-Issue")
    merged["seeded_from"] = {"case_handoff": True, "source_case_id": incoming}
    return validate_case_file(merged)


def build_team_binding(bound, team_url=None, channel=None, decided_on=None):
    """`team_binding.json`. Written ONLY when a Team is actually bound (SKILL.md Step 0a:
    on 'No Team yet' or 'Not sure of the URL', do NOT write this file)."""
    if not bound:
        raise SchemaError(
            "refusing to write team_binding.json for an unbound case. SKILL.md is explicit: "
            "an unbound case has NO binding file, and writing one with bound=false is not "
            "the same thing. A present-but-false file reads as a decision that was made; "
            "an absent file reads as a decision still open."
        )
    if not (team_url or "").strip():
        raise SchemaError("a bound case needs a team_url; that is what binding means")
    return {"binding": {"bound": True, "team_url": team_url.strip(),
                        "channel": channel, "decided_on": decided_on}}


def build_project_ack(acknowledged, acknowledged_on=None):
    """`rfx_project_acknowledged.json`, the gate that stops Step 0a re-running."""
    if not acknowledged:
        raise SchemaError(
            "refusing to write an acknowledgement file that records a non-acknowledgement. "
            "Its presence is the signal; SKILL.md skips Step 0a on any run where the file "
            "is FOUND, so a file saying false would skip the step it was meant to gate."
        )
    return {"acknowledged": True, "acknowledged_on": acknowledged_on}


MEETING_COLUMNS = ["meeting_id", "date", "type", "attendees", "purpose",
                   "decisions", "actions", "status"]
MEETING_STATUS = ("draft", "sent", "completed", "cancelled")


def write_meeting_log(rows, path):
    """`meeting_log.csv`. Fixed columns, validated status enum, unique ids."""
    _unique(rows, "meeting_id", "meeting_log")
    for i, r in enumerate(rows or []):
        st = r.get("status")
        if st is not None:
            _enum(st, MEETING_STATUS, "meeting_log[%d].status" % i)
    with open(path, "w", encoding="utf-8", newline="") as fh:
        w = csv.DictWriter(fh, fieldnames=MEETING_COLUMNS, extrasaction="ignore")
        w.writeheader()
        for r in rows or []:
            w.writerow(r)
    return path


def write_json(obj, path):
    with open(path, "w", encoding="utf-8") as fh:
        json.dump(obj, fh, indent=2)
    return path


def main(argv):
    if not argv:
        print(__doc__.strip())
        print("\nusage: case_state_generator.py <case_file.json>   # validate")
        return 0
    with open(argv[0], encoding="utf-8") as fh:
        case = json.load(fh)
    try:
        validate_case_file(case)
    except CaseStateError as e:
        print("REFUSED: %s: %s" % (type(e).__name__, e), file=sys.stderr)
        return 2
    print("OK: case %s validates against schema %s" % (case["case_id"], SCHEMA_VERSION))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
