// Evidence check for the Deep Dive v3 structure (6 visual subtabs on pvAssess).
'use strict';
const vm = require('vm'); const fs = require('fs'); const path = require('path');
const A = path.join(__dirname, 'assets'); const R = p => fs.readFileSync(path.join(A, p), 'utf8');
const js = R('pv/pv-01-boot-helpers.js')+'\n'+R('pv/pv-04-domain-data.js')+'\n'+R('pv/pv-07a-assess-model.js')+'\n'+R('pv/pv-07-landscape-render.js')+'\n'+R('pv/pv-07b-deepdive.js')+'\n'+R('pv-extracted-helpers.js')+'\n'+R('landscape-data.js');
const ctx = {}; ctx.window = ctx; ctx.self = ctx;
ctx.document = { getElementById:()=>({innerHTML:'',style:{},classList:{add(){},remove(){},toggle(){}}}), querySelector:()=>({innerHTML:'',style:{}}), querySelectorAll:()=>[], createElement:()=>({style:{},classList:{add(){},remove(){},toggle(){}},setAttribute(){},appendChild(){},getContext:()=>({})}), addEventListener(){}, body:{appendChild(){},style:{}} };
ctx.localStorage = { getItem:()=>null, setItem(){}, removeItem(){} }; ctx.requestAnimationFrame = ()=>0; ctx.location = { hash:'' }; ctx.console = console;
vm.createContext(ctx); vm.runInContext(js, ctx, { filename:'concat.js' });
const render = ddt => { ctx.PVSL_SUB='deep'; ctx.curtab='landscape'; ctx.PVSL_DDT=ddt; return ctx.landscapeHTML(); };
let fails = 0;
const has = (l,h,s)=>{const ok=h.includes(s);console.log((ok?'PASS':'FAIL')+' '+l+' :: has "'+s+'"');if(!ok)fails++;};
const not = (l,h,s)=>{const ok=!h.includes(s);console.log((ok?'PASS':'FAIL')+' '+l+' :: absent "'+s+'"');if(!ok)fails++;};
const sum = render('summary');
console.log('--- shell / tabs ---');
['Supplier Summary','Company &amp; Ownership','Capabilities &amp; Operations','Financial &amp; Market','Risk &amp; Resilience','Lilly Fit &amp; Diligence'].forEach(t=>has('tabbar',sum,'>'+t+'</button>'));
not('tabbar',sum,'>Profile</button>'); not('tabbar',sum,'>Requirements Fit</button>');
console.log('--- compact decision header (replaces 2 bands + composite) ---');
has('header',sum,'Recommendation'); has('header',sum,'Advance with conditions'); has('header',sum,'Evidence confidence'); has('header',sum,'Open issues');
not('header',sum,'INVITE'); not('header',sum,'Competitive position');
console.log('--- Summary content ---');
has('summary',sum,'Assessment across eight dimensions'); has('summary',sum,'Identity &amp; ownership'); has('summary',sum,'Financial viability'); has('summary',sum,'Evidence coverage'); has('summary',sum,'Reasons to advance'); has('summary',sum,'ESCALATE');
console.log('--- other tabs render their lead ---');
has('company',render('company'),'Ownership &amp; control');
has('caps',render('caps'),'Offering &amp; delivery');
has('finmkt',render('finmkt'),'Financial viability');
has('risk',render('risk'),'Risk posture by dimension'); has('risk',render('risk'),'UNC5537');
has('lilly',render('lilly'),'Required diligence');
console.log('\n'+(fails?fails+' FAILURE(S)':'ALL DD2 CHECKS PASSED'));
process.exit(fails?1:0);
